---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: poolboy deploy
  name: poolboy-build

parameters:
- name: GIT_REPO
  value: https://github.com/redhat-cop/poolboy.git
- name: SERVICE_NAME
  value: poolboy

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${SERVICE_NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${SERVICE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SERVICE_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: quay.io/jkupferer/python-kopf-s2i:v0.28
    triggers: []
