---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: poolboy deploy
  name: poolboy-build

parameters:
- name: NAME
  value: poolboy
- name: GIT_REPO
  value: https://github.com/redhat-cop/poolboy.git
- name: GIT_REF
  value: main
- name: KOPF_S2I_IMAGE
  value: quay.io/redhat-cop/python-kopf-s2i:v1.36
- name: PYTHON_S2I_IMAGE
  value: registry.access.redhat.com/ubi8/python-38:latest

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: ${KOPF_S2I_IMAGE}
    triggers: []

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}-admin
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}-admin
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-admin:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: admin
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: true
    triggers: []

#- apiVersion: image.openshift.io/v1
#  kind: ImageStream
#  metadata:
#    name: ${NAME}-admin-api
#  spec:
#    lookupPolicy:
#      local: false
#
#- apiVersion: v1
#  kind: BuildConfig
#  metadata:
#    name: ${NAME}-admin-api
#  spec:
#    output:
#      to:
#        kind: ImageStreamTag
#        name: ${NAME}-admin-api:latest
#    postCommit: {}
#    resources: {}
#    runPolicy: Serial
#    source:
#      contextDir: admin-api
#      git:
#        uri: ${GIT_REPO}
#        ref: ${GIT_REF}
#    strategy:
#      type: Source
#      sourceStrategy:
#        from:
#          kind: DockerImage
#          name: ${PYTHON_S2I_IMAGE}
#    triggers: []
#
#- apiVersion: image.openshift.io/v1
#  kind: ImageStream
#  metadata:
#    name: ${NAME}-admin-ui
#  spec:
#    lookupPolicy:
#      local: false
#
#- apiVersion: v1
#  kind: BuildConfig
#  metadata:
#    name: ${NAME}-admin-ui
#  spec:
#    output:
#      to:
#        kind: ImageStreamTag
#        name: ${NAME}-admin-ui:latest
#    postCommit: {}
#    resources: {}
#    runPolicy: Serial
#    source:
#      contextDir: admin-ui
#      git:
#        uri: ${GIT_REPO}
#        ref: ${GIT_REF}
#    strategy:
#      type: Docker
#      dockerStrategy:
#        forcePull: true
#    triggers: []
