# Poolboy Development

Poolboy development can be performed in the `odo` OpenShift developer CLI or building with OpenShift build configs.
Use of `odo` is recommended for fast iterative development.

## Using odo

The `odo` developer CLI can be installed as described in the OpenShift documentation:

https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html[Installing odo]

To run with `odo`, first create the `python-kopf` ImageStream definition in the `openshift` namespace using the Red Hat Community of Practice containers-quickstarts repository.

--------------------------------------------------------------------------------
oc apply -f https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/master/build-s2i-python-kopf/imagestream.yaml
--------------------------------------------------------------------------------

Create poolboy resources from the provided deploy template:

--------------------------------------------------------------------------------
oc process --local -f deploy-template.yaml -p NAMESPACE=poolboy | oc apply -f -
--------------------------------------------------------------------------------

Scale down the poolboy deployment:

----------------------------------------
oc scale deployment poolboy --replicas=0
----------------------------------------

Use `odo create` to setup configuration for beginning work on Poolboy:

-----------------------------------------------------------------------------
odo create python-kopf poolboy
-----------------------------------------------------------------------------

Use `odo push` to create an `anarchy-app` DeploymentConfig and Service.

--------
odo push
--------

Patch the poolboy-app DeploymentConfig to associate the service account

-------------------------------------------------------------------------
oc patch dc/poolboy-app \
--patch '{"spec":{"template":{"spec":{"serviceAccountName":"poolboy"}}}}'
-------------------------------------------------------------------------

Push once more do refresh after the service account restart.

-----------------------------------------------------------------------------
odo push --force-build
-----------------------------------------------------------------------------

## OpenShift Build

. Process OpenShift build template to create BuildConfig and ImageStream
+
----
oc process --local -f build-template.yaml | oc apply -n poolboy -f -
----

. Build poolboy image
+
----
oc start-build poolboy -n poolboy --from-dir=. --follow
----

. Deploy Poolboy from build image
+
----
oc process --local \
  -f deploy-template.yaml \
  -p NAMESPACE=poolboy \
  -p IMAGE=$(oc get imagestream poolboy -n poolboy -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].dockerImageReference}') \
| oc apply -n poolboy -f -
----
