{{- if .Values.admin.deploy -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "poolboy.name" . }}-admin
  namespace: {{ include "poolboy.namespaceName" . }}
spec:
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: {{ include "poolboy.name" . }}-admin

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "poolboy.name" . }}-admin-tls
  name: {{ include "poolboy.name" . }}-admin
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
spec:
  ports:
  - name: proxy
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "poolboy.adminSelectorLabels" . | nindent 4 }}
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "poolboy.name" . }}-admin"}}
  name: {{ include "poolboy.name" . }}-admin
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poolboy.name" . }}-admin
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      {{- include "poolboy.adminSelectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "poolboy.adminSelectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: app
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "poolboy.name" . }}-admin-redis
              key: database-password
        - name: REDIS_SERVER
          value: {{ include "poolboy.name" . }}-admin-redis
        - name: REDIS_PORT
          value: "6379"
        image: "{{ include "poolboy.adminImage" . }}"
        imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 5000
          timeoutSeconds: 1
      - name: oauth-proxy
        args:
        - --https-address=:8443
        - --provider=openshift
        - --openshift-service-account={{ include "poolboy.name" . }}-admin
        - --upstream=http://localhost:5000
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --cookie-secret=SECRET
        image: openshift/oauth-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: public
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/tls/private
          name: proxy-tls
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "poolboy.name" . }}-admin
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: proxy-tls
        secret:
          defaultMode: 0644
          secretName: {{ include "poolboy.name" . }}-admin-tls

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "poolboy.name" . }}-admin"
rules:
- apiGroups:
  - ""
  - user.openshift.io
  resources:
  - users
  verbs:
  - impersonate

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "poolboy.name" . }}-admin"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "poolboy.name" . }}-admin"
subjects:
- kind: ServiceAccount
  name: "{{ include "poolboy.name" . }}-admin"
  namespace: {{ include "poolboy.namespaceName" . }}

{{- if .Values.admin.redisPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poolboy.name" . }}-admin-redis
  namespace: {{ include "poolboy.namespaceName" . }}
data:
  {{- if eq .Values.admin.redisPassword "generate" }}
  database-password: {{ randAlphaNum 32 | b64enc }}
  {{- else }}
  database-password: {{ .Values.admin.redisPassword | b64enc }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "poolboy.name" . }}-admin-redis
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    {{- include "poolboy.redisSelectorLabels" . | nindent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poolboy.name" . }}-admin-redis
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "poolboy.redisSelectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "poolboy.redisSelectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ include "poolboy.name" . }}-admin-redis
        image: {{ .Values.admin.redisImage | quote }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 1
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - test "$(redis-cli -h 127.0.0.1 -a $REDIS_PASSWORD ping)" == "PONG"
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: redis-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: redis-data
{{- end }}
