{{- if .Values.anarchy.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "poolboy.name" . }}:{{ .Values.anarchy.namespace }}:{{ .Values.anarchy.service }}
rules:
- apiGroups:
  - {{ include "poolboy.operatorDomain" . }}
  resources:
  - resourceclaims
  - resourcehandles
  verbs:
  - delete
  - get
  - list
  - patch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "poolboy.name" . }}:{{ .Values.anarchy.namespace }}:{{ .Values.anarchy.service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "poolboy.name" . }}:{{ .Values.anarchy.namespace }}:{{ .Values.anarchy.service }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.anarchy.namespace }}
  name: {{ .Values.anarchy.service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "poolboy.namespaceName" . }}:{{ include "poolboy.name" . }}
  namespace: {{ .Values.anarchy.namespace }}
rules:
- apiGroups:
  - {{ .Values.anarchy.domain }}
  resources:
  - anarchysubjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.anarchy.namespace }}:{{ include "poolboy.namespaceName" . }}:{{ include "poolboy.name" . }}
  namespace: {{ .Values.anarchy.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "poolboy.namespaceName" . }}:{{ include "poolboy.name" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ include "poolboy.namespaceName" . }}
  name: {{ include "poolboy.name" . }}
{{- end -}}
