---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "poolboy.name" . }}-aggregate-to-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - {{ include "poolboy.operatorDomain" . }}
  resources:
  - resourceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "poolboy.name" . }}-aggregate-to-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - {{ include "poolboy.operatorDomain" . }}
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "poolboy.name" . }}
rules:
- apiGroups:
  - {{ include "poolboy.operatorDomain" . }}
  resources:
  - resourceproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ include "poolboy.operatorDomain" . }}
  resources:
  - resourceclaims
  - resourceclaims/status
  - resourcehandles
  - resourcehandles/status
  - resourcepools
  - resourcepools/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - user.openshift.io
  resources:
  - users
  - identities
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
{{ if .Values.deploy -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "poolboy.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "poolboy.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "poolboy.serviceAccountName" . }}
  namespace: {{ include "poolboy.namespaceName" . }}
{{- end -}}
