{{- if .Values.crds.create -}}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcepools.{{ include "poolboy.operatorDomain" . }}
spec:
  group: {{ include "poolboy.operatorDomain" . }}
  version: v1
  scope: Namespaced
  names:
    plural: resourcepools
    singular: resourcepool
    kind: ResourcePool
    shortNames: []
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: >-
        ResourcePools are used to manage a reserve number of unclaimed ResourceHandles.
      type: object
      required:
      - apiVersion
      - kind
      - metadata
      - spec
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          description: ResourcePool specification
          type: object
          required:
          - resources
          properties:
            minAvailable:
              description: >-
                Minimum number of unclaimed resource handles to maintain for the
                ResourcePool.
              type: integer
              minimum: 0
            resources:
              description: >-
                Resources description to apply to ResourceHandles for the pool.
              type: array
              items:
                type: object
                required:
                - provider
                - template
                properties:
                  provider:
                    description: Reference to ResourceProvider
                    type: object
                    required:
                    - apiVersion
                    - kind
                    - name
                    - namespace
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                  template:
                    description: Resource template for ResourceHandle
                    type: object
{{- end -}}
