{{- if .Values.crds.create -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceproviders.{{ include "poolboy.operatorDomain" . }}
spec:
  group: {{ include "poolboy.operatorDomain" . }}
  scope: Namespaced
  names:
    plural: resourceproviders
    singular: resourceprovider
    kind: ResourceProvider
  versions:
  - name: v1
    served: true
    storage: true
    additionalPrinterColumns:
    - name: Api Version
      type: string
      jsonPath: .spec.override.apiVersion
    - name: Kind
      type: string
      jsonPath: .spec.override.kind
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        description: >-
          ResourceProviders describe how to manage resources from settings in ResourceClaims and
          ResourceHandles.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
          spec:
            description: >-
              Specification of how the ResourceProvider should manage resources.
            type: object
            properties:
              approval:
                description: >-
                  Approval configuration for ResourceClaims.
                type: object
                properties:
                  pendingMessage:
                    description: >-
                      Message to add to approval status when initially pending.
                      If unset then "Approval pending." will be used.
                    type: string
                  required:
                    description: >-
                      Boolean to mark that approval is required.
                    type: boolean
              default:
                description: >-
                  Template applied to resource claims immediately after matching to the provider
                  to set default values into the claim when not present.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              disableCreation:
                description: >-
                  If set to true, then ResourceHandle creation is disabled for any ResourceClaim using
                  this ResourceProvider.
                type: boolean
              lifespan:
                description: >-
                  Used to generate lifespan configuration for ResourceHandles using the ResourceProvider.
                type: object
                properties:
                  default:
                    description: >-
                      Default lifespan for ResourceHandle when it is claimed.
                      Configured as a whole number followed by units "s", "m", "h", or "d" for seconds, minutes, hours, or days.
                      Ex: "3d" for 3 days.
                      This value may be a template string.
                    type: string
                  maximum:
                    description: >-
                      Maximum lifespan which may be requested in the ResourceClaim relative to the creation timestamp.
                      Configured as a whole number followed by units "s", "m", "h", or "d" for seconds, minutes, hours, or days.
                      Ex: "3d" for 3 days.
                      This value may be a template string.
                    type: string
                  relativeMaximum:
                    description: >-
                      Maximum lifespan which may be requested in the ResourceClaim relative to the present datetime.
                      Configured as a whole number followed by units "s", "m", "h", or "d" for seconds, minutes, hours, or days.
                      Ex: "3d" for 3 days.
                      This value may be a template string.
                    type: string
              linkedResourceProviders:
                description: >-
                  List of ResourceProviders this one depends upon.
                  Values from resources provided by linked providers can be referenced in template vars.
                type: array
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      description: >-
                        Name of linked ResourceProvider
                      type: string
                    parameterValues:
                      description: >-
                        Parameter values to pass to linked resource provider when ResourceClaim uses top-level provider specification.
                        Values are automatically processed for jinja2 template strings to allow passing parameter values directly, filtered, or with conditional logic.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    resourceName:
                      description: >-
                        Resource name to use when generating resources list for provider.
                      type: string
                    templateVars:
                      description: >-
                        Variables to make available to templating from linked ResourceProvider.
                        These variables propagate up from the resource.
                      type: array
                      items:
                        type: object
                        required:
                        - from
                        - name
                        properties:
                          from:
                            description: >-
                              Source path from resource state given in JSON Pointer (IETF RFC 6901) format.
                              (ex: /spec/metadata/name).
                            type: string
                          name:
                            description: >-
                              Name of template variable to set.
                            type: string
                    waitFor:
                      description: >-
                        Condition to wait for in linked provider before creating resource.
                        Condition is given in Jinja2 syntax similar to ansible "when" clauses.
                        The linked provider's resource state may be referenced with "resource_state".
                      type: string
              match:
                description: >-
                  Partial resource definition used to check if a resource in a handle or claim
                  matches this provider.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              matchIgnore:
                description: >-
                  Regular expressions used to filter out differences between a resources in
                  a claim or when matching to a handle. Comparison is made by generating a
                  JSON Patch (RFC 6902) comparison between the resource definitions. If any
                  of these regular expressions matches the JSON Pointer (IETF 6901) path
                  component of the patch then it is ignored.
                type: array
                items:
                  type: string
              override:
                description: >-
                  Override template that is merged with the ResourceHandle resource template to
                  generate the final resource definition.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              parameters:
                type: array
                items:
                  type: object
                  properties:
                    allowUpdate:
                      description: >-
                        Control whether this boolean may be updated after initially set.
                      type: boolean
                    default:
                      description: >-
                        Default value for this parameter when no value is provided.
                        The default includes support for a default template or value.
                        The value is not explictly listed in the schema as kubernetes does not support undefined types.
                        If both template and value are set then template is used.
                      type: object
                      properties:
                        template:
                          description: >-
                            Jinja2 template string used to generate default value.
                          type: string
                      # Supports field "value" with undefined type
                      x-kubernetes-preserve-unknown-fields: true
                    name:
                      type: string
                    required:
                      description: >-
                        Configure whether parameter value is required.
                      type: boolean
                    validation:
                      type: object
                      properties:
                        checks:
                          description: >-
                            Check parameter value using Jinja2 expressions.
                          type: array
                          items:
                            type: object
                            required:
                            - name
                            - check
                            properties:
                              name:
                                description: >-
                                  Descriptive name of what is checked to communicate when check fails.
                                type: string
                              check:
                                description: >-
                                  Jinja2 expression which must evaluate to a true value for the ResourceClaim
                                  resource template to be valid.
                                type: string
                        openAPIV3Schema:
                          description: >-
                            OpenAPI 3.0 data model (schema) used to validate the parameter value.
                            This is the same schema specification used by CustomResourceDefinitions (CRDs)
                            but with support for additional features supported such as disallowing
                            additional properties of objects. These schemas can be used to place limits
                            on resource definitions beyond the definition of the cluster API such as to
                            restrict a string field to a particular set of allowed values or numeric
                            fields to specific numeric ranges.
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
              resourceClaimAnnotations:
                description: >-
                  Annotations to apply to ResourceClaim.
                type: object
                additionalProperties:
                  type: string
              resourceClaimLabels:
                description: >-
                  Labels to apply to ResourceClaim.
                type: object
                additionalProperties:
                  type: string
              resourceName:
                description: >-
                  Name to apply to resource list entry when resources list is generated.
                type: string
              resourceRequiresClaim:
                description: >-
                  Flag to indicate that creation of resource for handle should waint until a claim
                  is bound.
                type: boolean
              statusSummaryTemplate:
                description: >-
                  Object template for generating ResourceClaim status.summary from current state.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              template:
                description: >-
                  Template settings for the ResourceProvider. Applied to override and defaults.
                type: object
                properties:
                  definition:
                    description: >-
                      Definition used to generate resource template using parameters.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  enable:
                    description: Explicit enable or disable of templates.
                    type: boolean
                  style:
                    description: >-
                      Template style. Currently only "jinja2" is supported.
                    type: string
                    enum:
                    - jinja2
              updateFilters:
                description: >-
                  Restrictions to apply to changes which can propagate from the ResourceClaim
                  resource template to the ResourceHandle resource template.
                type: array
                items:
                  type: object
                  required:
                  - pathMatch
                  properties:
                    allowedOps:
                      description: >-
                        List of operations that are allowed propagate from the ResourceClaim to the
                        ResourceHandle resource definition. These are checked against the generated
                        JSON Patch items which may have verbs "add", "replace", and "remove". If
                        not given, then all operations are allowed.
                      type: array
                      items:
                        type: string
                    pathMatch:
                      description: >-
                        Regular expression used to match against the calculated JSON Patch path.
                        Regular expressions must match the entire path.
                      type: string
              validation:
                description: >-
                  Validation to apply to ResourceClaim resource templates.
                type: object
                properties:
                  checks:
                    description: >-
                      Check resource template using Jinja2 expressions.
                    type: array
                    items:
                      type: object
                      required:
                      - name
                      - check
                      properties:
                        name:
                          description: >-
                            Descriptive name of what is checked to communicate when check fails.
                          type: string
                        check:
                          description: >-
                            Jinja2 expression which must evaluate to a true value for the ResourceClaim
                            resource template to be valid.
                          type: string
                  openAPIV3Schema:
                    description: >-
                      OpenAPI 3.0 data model (schema) used to validate ResourceClaim resource templates.
                      This is the same schema specification used by CustomResourceDefinitions (CRDs)
                      but with support for additional features supported such as disallowing
                      additional properties of objects. These schemas can be used to place limits
                      on resource definitions beyond the definition of the cluster API such as to
                      restrict a string field to a particular set of allowed values or numeric
                      fields to specific numeric ranges.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
              vars:
                description: >-
                  Additional variables to use when evaluating validation checks and templates.
                  Variables in a ResourceHandle override variables in the ResourceProvider.
                type: object
                x-kubernetes-preserve-unknown-fields: true
{{- end -}}
