---
apiVersion: poolboy.gpte.redhat.com/v1
kind: ResourceProvider
metadata:
  name: anarchy-subject
  namespace: poolbay
spec:
  match:
    apiVersion: gpte.redhat.com/v1
    kind: AnarchySubject
    metadata:
      annotations:
        gpte.redhat.com/resource-provider-name: anarchy-subject
        gpte.redhat.com/resource-provider-namespace: poolboy
  default: {}
  override:
    metadata:
      generateName: babylon1-agnosticd-
      namespace: anarchy-operator
      labels:
        gpte.redhat.com/anarchy-governor: babylon1-agnosticd
    spec:
      governor: babylon1-agnosticd
      parameters:
        guid: >-
          {{: resource_handle.metadata.name[5:]
           if resource_handle.metadata.name.startswith('guid-')
           else resource_handle.metadata.name :}}
  updateFilters:
  - pathMatch: /spec/desiredState
  validation:
    openAPIV3Schema:
      type: object
      required:
      - apiVersion
      - kind
      - spec
      additionalProperties: false
      properties:
        apiVersion:
          type: string
          enum:
          - gpte.redhat.com/v1
        kind:
          type: string
          enum:
          - AnarchySubject
        metadata:
          type: object
          additionalProperties: false
          properties:
            annotations:
              type: object
              additionalProperties:
                type: string
            labels:
              type: object
              additionalProperties:
                type: string
            namespace:
              type: string
        spec:
          type: object
          required:
          - parameters
          additionalProperties: false
          properties:
            desiredState:
              type: string
              enum:
              - started
              - stopped
            governor:
              type: string
            parameters:
              type: object
