---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: poolboy resourceprovider deploy
  name: poolboy-resourceprovider-deploy
objects:
- apiVersion: poolboy.gpte.redhat.com/v1
  kind: ResourceProvider
  metadata:
    name: babylon
    namespace: "${NAMESPACE}" 
  spec:
    default:
      spec:
        desiredState: started
    match:
      apiVersion: anarchy.gpte.redhat.com/v1
      kind: AnarchySubject
      metadata:
        annotations:
          poolboy.gpte.redhat.com/resource-provider-name: babylon
    matchIgnore:
    - /spec/desiredState
    override:
      metadata:
        namespace: "${ANARCHY_NAMESPACE}"
      spec:
        vars:
          babylon_user_email: >-
            {{: requester_identity.extra.email | default(None) if requester_identity else None :}}
          babylon_user_fullname: >-
            {{: requester_identity.extra.name | default(None) if requester_identity else None :}}
          babylon_username: >-
            {{: requester_user.metadata.name | default(None) if requester_user else None :}}
          job_vars:
            guid: >-
              {{: resource_handle.metadata.name[-5:] :}}
    updateFilters:
    - pathMatch: /spec/desiredState
    validation:
      openAPIV3Schema:
        type: object
        additionalProperties: false
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
            enum:
            - anarchy.gpte.redhat.com/v1
          kind:
            type: string
            enum:
            - AnarchySubject
          metadata:
            type: object
            additionalProperties: false
            properties:
              annotations:
                additionalProperties:
                  type: string
                type: object
              generateName:
                type: string
              labels:
                additionalProperties:
                  type: string
                type: object
          spec:
            type: object
            required:
            - governor
            additionalProperties: false
            properties:
              desiredState:
                enum:
                - started
                - stopped
                type: string
              governor:
                type: string
              vars:
                type: object
parameters:
- name: NAMESPACE
  value: poolboy
- name: ANARCHY_NAMESPACE
  value: anarchy-operator
