apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcepools.poolboy.gpte.redhat.com
spec:
  group: poolboy.gpte.redhat.com
  scope: Namespaced
  names:
    plural: resourcepools
    singular: resourcepool
    kind: ResourcePool
    shortNames: []
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Min
      type: integer
      jsonPath: .spec.minAvailable
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        description: >-
          ResourcePools are used to manage a reserve number of unclaimed ResourceHandles.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
          spec:
            description: ResourcePool specification
            type: object
            required:
            - resources
            properties:
              lifespan:
                description: >-
                  Lifespan configuration for ResourceHandle provisioned by the ResourcePool.
                type: object
                properties:
                  default:
                    description: >-
                      Default lifespan to apply to ResourceHandle when it is claimed from the pool.
                      Configured as a whole number followed by units "s", "m", "h", or "d" for seconds, minutes, hours, or days.
                      Ex: "3d" for 3 days.
                      This value may be a template string.
                    type: string
                  maximum:
                    description: >-
                      Maximum lifespan which may be requested in the ResourceClaim relative to the creation timestamp of the ResourceClaim.
                      Configured as a whole number followed by units "s", "m", "h", or "d" for seconds, minutes, hours, or days.
                      Ex: "3d" for 3 days.
                      This value may be a template string.
                    type: string
                  relativeMaximum:
                    description: >-
                      Maximum lifespan which may be requested in the ResourceClaim relative to the present datetime.
                      Configured as a whole number followed by units "s", "m", "h", or "d" for seconds, minutes, hours, or days.
                      Ex: "3d" for 3 days.
                      This value may be a template string.
                    type: string
                  unclaimed:
                    description: >-
                      Lifespan applied to ResourceHandles in the pool to allow for replacement of unused resources.
                      Configured as a whole number followed by units "s", "m", "h", or "d" for seconds, minutes, hours, or days.
                      Ex: "3d" for 3 days.
                    type: string
                    pattern: ^[0-9]+[smhd]$
              minAvailable:
                description: >-
                  Minimum number of unclaimed resource handles to maintain for the
                  ResourcePool.
                type: integer
                minimum: 0
              resources:
                description: >-
                  Resources description to apply to ResourceHandles for the pool.
                type: array
                items:
                  type: object
                  required:
                  - provider
                  properties:
                    name:
                      description: >-
                        A name used to identify the resource.
                      type: string
                    provider:
                      description: Reference to ResourceProvider
                      type: object
                      required:
                      - apiVersion
                      - kind
                      - name
                      - namespace
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                    template:
                      description: Resource template for ResourceHandle
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
          status:
            description: ResourcePool status
            type: object
            properties:
              diffBase:
                description: Kopf diffbase
                type: string
              kopf:
                description: Kopf status
                type: object
                x-kubernetes-preserve-unknown-fields: true
