apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceclaims.poolboy.gpte.redhat.com
spec:
  group: poolboy.gpte.redhat.com
  scope: Namespaced
  names:
    plural: resourceclaims
    singular: resourceclaim
    kind: ResourceClaim
    shortNames: []
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Handle
      type: string
      jsonPath: .status.resourceHandle.name
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        description: >-
          ResourceClaims describe a request for one or more resources to be created within the cluster.
          ResourceClaims will are first checked for validity against ResourceProviders and then matched
          to a ResourceHandle or a ResourceHandle is created dynamically.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-._]*[a-z0-9A-Z])?$
          spec:
            description: ResourceClaim specification
            type: object
            properties:
              resources:
                type: array
                items:
                  type: object
                  properties:
                    provider:
                      description: >-
                        ResourceProvider specification that is used to manage the resource template.
                        The provider may be specified explicitly or discovered by matching against the
                        template.
                      type: object
                      required:
                      - name
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                    template:
                      description: >-
                        Resource template which is matched to and evaluated against a ResourceProvider.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
          status:
            description: ResourceClaim status
            type: object
            properties:
              resourceHandle:
                description: ResourceHandle reference for handle matched to this claim
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
              resources:
                description: Status of resources managed for this claim
                type: array
                items:
                  type: object
                  properties:
                    provider:
                      description: ResourceProvider reference for provider managing this resource
                      type: object
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                    state:
                      description: Resource state synchronized from managed resource
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
